### ISSUE TITLE
Test issue 

### ISSUE THREAD

**Issue by MohammedAlMaqbli** [learn-co-curriculum/css-essentials-css-fundamentals-lab#2]
When I first run learn in my local environment after just simply link the style.css  file. Learn pass all tests successfully  and even-though  my index page does not look like, learn say" the finished product looks like the finished product". So please fix it

**Comment by sgharms** [comment]
Hi @MohammedAlMaqbli Some of our tests have really simple tests in place to "trigger" learn to give a programming environment. It's a feature request for the platform, but this is our workaround for the moment. Before long, you'll have lots of "real" things to fix in your tests, we promise! We'll add your input to our feature request. As such, I'm going to close this issue.

Our apologies for any confusion.
